name: Crawl (full)

on:
  workflow_dispatch:

jobs:
  crawl:
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/crawl-reusable.yaml
    with:
      run_type: full
    secrets: inherit
